Frontend:
  impl: BHO3
  clock_ratio: 8
  llc_capacity_per_core: 2MB
  llc_num_mshr_per_core: 16
  num_expected_insts: 100000000
  num_max_cycles: 500000000
  llc_deserialize: true
  llc_deserialization_filename: ./test.llc
  inst_window_depth: 128
  traces: 
    - ./test.trace

  Translation:
    impl: RandomTranslation
    max_addr: 17179869184

MemorySystem:
  impl: BHDRAMSystem
  clock_ratio: 3

  DRAM:
    impl: DDR5-RVRR
    latency_factor_vrr: 1.0
    latency_factor_rfc: 1.0
    drampower_enable: true
    org:
      preset: DDR5_16Gb_x8
      channel: 1
      rank: 2
    timing:
      preset: DDR5_3200AN 
    voltage:
      preset: Default
    current:
      preset: Default

  BHDRAMController:
    impl: BHDRAMController
    BHScheduler:
      impl: BHScheduler
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: ClosedRowPolicy
      cap: 4
    plugins:
      - ControllerPlugin:
          impl: CommandCounter
          path: ./test.cmds1
          commands_to_count:
            - ACT
            - PRE
            - VRR

  AddrMapper:
    impl: RoBaRaCoCh_with_rit